#!/usr/bin/env python3
"""
filter_sequences.py

Builds a degenerate-motif representation from a set of aligned, mutated
protein sequences, based on per-position amino acid frequency.

ALGORITHM (per aligned position):
  1. Count each amino acid's occurrences at that position, IGNORING gaps
     ('-') and ambiguous residues ('X'). Proportions are computed only
     over real (standard) amino acid calls at that position.
  2. Sort the observed amino acids at that position by proportion,
     descending.
  3. The single highest-proportion amino acid is the "top" residue at
     that position.
  4. The remaining proportion mass (1 - top_proportion) is multiplied by
     --proportion (default 0.5) to get a threshold. Walk down the sorted
     list (excluding the top one) and keep adding amino acids to that
     position's "extra" list, accumulating their proportions, for as
     long as the running total does not exceed the threshold. The first
     amino acid that would push the cumulative sum over the threshold is
     excluded, and no further (smaller-proportion) amino acids are
     considered for that position (strict sequential walk, not a
     best-fit search).
     This "extra" list, together with the top residue, forms that
     position's ALLOWED SET.

BASE SEQUENCE (two modes, toggled with --random-base):
  - Default (original/consensus mode): the base sequence is built from
    the top-scoring amino acid at every position -- i.e. the
    highest-proportion "original"/wild-type residue.
  - --random-base mode: there is no privileged "original" sequence.
    Instead, a base sequence is randomly generated by picking, at each
    position, uniformly at random from that position's allowed set (top
    + extras). This sequence is then used exactly the same way the
    consensus would be -- listed first, with per-position variants built
    off it -- but it is NOT labelled/reported as an "original" or
    "consensus" sequence, since it isn't one.

OUTPUT:
  A FASTA file:
    - the first record ">1" is the base sequence (top-scoring consensus,
      or the randomly generated sequence if --random-base is set)
    - one additional numbered record for EVERY (position, allowed amino
      acid) pair where that amino acid differs from the base sequence's
      residue at that position. Each such record is the base sequence
      with ONLY that one position swapped -- every other position stays
      at its base residue.

  Example, for a 12-residue motif where position 1 has two extra
  amino acids (T, M) and position 2 has one extra amino acid (S):

      >1
      AVASIOCNAIJF
      >2
      TVASIOCNAIJF
      >3
      MVASIOCNAIJF
      >4
      ASASIOCNAIJF

  (A per-position breakdown with labels like "pos 1a"/"pos 1b" is
  still available via the optional --report TSV, for inspection.)

  Optionally, a separate TSV report can also be written, giving the
  full proportion breakdown computed at every position (useful for
  double-checking the thresholding).

NOTES / EDGE CASES:
  - All input sequences must be the same length (i.e. already aligned).
    The script raises an error if they are not.
  - If a position has zero real (non-gap/non-X) residues across every
    input sequence, there's nothing to build a distribution from. That
    position is marked 'X' in the base sequence and contributes no
    variant rows. This is logged clearly in the report.
  - Floating-point comparisons use a small epsilon tolerance to avoid
    borderline proportions being excluded/included due to rounding.
  - --random-base uses Python's `random` module; pass --seed for
    reproducible output.

INPUT:  a FASTA file of aligned sequences, e.g.:

            >1
            seq1
            >2
            seq2
            >3
            seq3

        Sequences may be wrapped across multiple lines; headers are
        read but not otherwise used (sequences are processed in the
        order they appear in the file).

USAGE:
    python filter_sequences.py input.fasta output.fasta \
        [--report report.tsv] [--random-base] [--seed 42] \
        [--proportion 0.5]
"""

import argparse
import csv
import random
import string
import sys
from collections import Counter

GAP_CHARS = {"-", "."}
AMBIGUOUS_CHARS = {"X", "x"}
EPSILON = 1e-9


def read_sequences(fasta_path):
    """Read sequences from a FASTA file.

    Supports both single-line and multi-line (wrapped) sequences --
    any line not starting with '>' is treated as sequence data and
    appended to the current record until the next '>' header or EOF.
    """
    seqs = []
    current_lines = []

    def _flush():
        if current_lines:
            seq = "".join(current_lines).strip().upper()
            if seq:
                seqs.append(seq)

    with open(fasta_path, newline="", encoding="utf-8-sig") as f:
        for line in f:
            line = line.rstrip("\r\n")
            if not line.strip():
                continue
            if line.startswith(">"):
                _flush()
                current_lines = []
            else:
                current_lines.append(line.strip())
        _flush()

    if not seqs:
        raise ValueError(f"No sequences found in FASTA file: {fasta_path}")
    return seqs


def validate_equal_length(seqs):
    lengths = {len(s) for s in seqs}
    if len(lengths) > 1:
        raise ValueError(
            f"Input sequences are not all the same length (found lengths: "
            f"{sorted(lengths)}). They must already be aligned."
        )
    return lengths.pop()


def summarize_positions(seqs, seq_len, proportion=0.5):
    """
    Args:
        proportion: fraction of the *remaining* proportion mass (i.e.
            1 - top_proportion) to include as "extra" amino acids at
            each position. Default 0.5 (50%).

    Returns:
        position_info: list of dicts, one per position:
                        {'top': aa or None, 'extra': [aa, aa, ...]}
                        'extra' is ordered by descending proportion.
        report_rows:   list of dicts for the optional TSV report.
    """
    position_info = []
    report_rows = []

    for pos in range(seq_len):
        residues = [s[pos] for s in seqs]
        counts = Counter(
            r for r in residues if r not in GAP_CHARS and r not in AMBIGUOUS_CHARS
        )
        total = sum(counts.values())

        if total == 0:
            position_info.append({"top": None, "extra": []})
            report_rows.append(
                {
                    "position": pos + 1,
                    "top": "",
                    "extra": "",
                    "breakdown": "ALL GAP/AMBIGUOUS COLUMN",
                }
            )
            continue

        proportions = sorted(
            ((aa, c / total) for aa, c in counts.items()),
            key=lambda x: -x[1],
        )

        top_aa, top_p = proportions[0]
        remaining = 1.0 - top_p
        threshold = remaining * proportion

        extra = []
        cumulative = 0.0
        for aa, p in proportions[1:]:
            if cumulative + p <= threshold + EPSILON:
                extra.append(aa)
                cumulative += p
            else:
                break  # sequential walk: stop at first that overshoots

        position_info.append({"top": top_aa, "extra": extra})
        breakdown_str = ", ".join(f"{aa}:{p:.1%}" for aa, p in proportions)
        report_rows.append(
            {
                "position": pos + 1,
                "top": top_aa,
                "extra": "".join(extra),
                "breakdown": breakdown_str,
            }
        )

    return position_info, report_rows


def build_top_consensus(position_info):
    """Base sequence built from the top-scoring amino acid at every
    position (the original/wild-type-style consensus)."""
    return "".join(info["top"] if info["top"] else "X" for info in position_info)


def generate_random_base(position_info, rng):
    """Base sequence built by picking uniformly at random, at each
    position, from that position's allowed set (top + extras). Every
    position in the resulting sequence is guaranteed to be a member of
    the set formed at that position."""
    seq_chars = []
    for info in position_info:
        if info["top"] is None:
            seq_chars.append("X")
            continue
        allowed = [info["top"]] + info["extra"]
        seq_chars.append(rng.choice(allowed))
    return "".join(seq_chars)


def build_variant_rows(position_info, base_sequence, base_label):
    """
    Build the (label, sequence) rows: the base sequence itself, plus one
    single-position-swapped variant for every allowed amino acid (top +
    extras) at each position that differs from the base sequence's
    residue there.

    This works the same way regardless of whether base_sequence is the
    top-scoring consensus or a randomly generated sequence: only
    genuinely different swaps are emitted, so no redundant duplicate of
    the base sequence is ever produced.
    """
    rows = [(base_label, base_sequence)]
    letters = string.ascii_lowercase

    for pos, info in enumerate(position_info):
        if info["top"] is None:
            continue
        allowed = [info["top"]] + info["extra"]
        base_res = base_sequence[pos]

        idx = 0
        for aa in allowed:
            if aa == base_res:
                continue  # would be identical to the base sequence
            suffix = letters[idx] if idx < len(letters) else f"_{idx}"
            label = f"pos {pos + 1}{suffix}"
            variant_seq = base_sequence[:pos] + aa + base_sequence[pos + 1:]
            rows.append((label, variant_seq))
            idx += 1

    return rows


def count_matches(seqs, position_info):
    """How many of the original input sequences are fully consistent
    with the derived allowed sets (top + extra) at every position?
    Informational only -- not written to the output file."""
    allowed_sets = [
        (None if info["top"] is None else {info["top"], *info["extra"]})
        for info in position_info
    ]
    count = 0
    for seq in seqs:
        ok = True
        for pos, aa in enumerate(seq):
            allowed = allowed_sets[pos]
            if allowed is not None and aa not in allowed:
                ok = False
                break
        if ok:
            count += 1
    return count


def write_variant_fasta(path, rows):
    """Write rows as FASTA, numbering headers sequentially (>1, >2, ...).
    Internal labels (e.g. 'original', 'random_base', 'pos 3a') are not
    written to the FASTA -- every record is listed the same way."""
    with open(path, "w", newline="") as f:
        for i, (_label, seq) in enumerate(rows, start=1):
            f.write(f">{i}\n{seq}\n")


def write_report(path, report_rows):
    with open(path, "w", newline="") as f:
        writer = csv.writer(f, delimiter="\t")
        writer.writerow(["position", "top_aa", "extra_aa", "proportion_breakdown"])
        for row in report_rows:
            writer.writerow([row["position"], row["top"], row["extra"], row["breakdown"]])


def main():
    parser = argparse.ArgumentParser(
        description="Build a degenerate-motif variant table from aligned protein sequences."
    )
    parser.add_argument("input_fasta", help="Path to input FASTA file")
    parser.add_argument("output_fasta", help="Path to write the variant sequences (FASTA)")
    parser.add_argument(
        "--report", default=None, help="Optional path to write a per-position TSV report"
    )
    parser.add_argument(
        "--random-base",
        action="store_true",
        help=(
            "Disable use of the top-scoring amino acid as the base/'original' "
            "sequence. Instead, randomly generate a base sequence by picking "
            "one amino acid per position from that position's allowed set "
            "(top + extras). There is then no privileged 'original'/consensus "
            "sequence -- the random base is listed the same as any other row."
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed for --random-base, for reproducible output.",
    )
    parser.add_argument(
        "--proportion",
        type=float,
        default=0.5,
        help=(
            "Fraction (0-1) of the remaining proportion mass (1 - top "
            "proportion) to include as 'extra' amino acids at each position. "
            "Default: 0.5 (50%%)."
        ),
    )
    args = parser.parse_args()

    if not (0.0 <= args.proportion <= 1.0):
        parser.error("--proportion must be between 0 and 1")

    seqs = read_sequences(args.input_fasta)
    seq_len = validate_equal_length(seqs)

    position_info, report_rows = summarize_positions(seqs, seq_len, args.proportion)

    if args.random_base:
        rng = random.Random(args.seed)
        base_sequence = generate_random_base(position_info, rng)
        base_label = "random_base"
        mode_desc = "randomly generated (each position drawn from its allowed set)"
    else:
        base_sequence = build_top_consensus(position_info)
        base_label = "original"
        mode_desc = "top-scoring consensus (original/wild-type residue per position)"

    rows = build_variant_rows(position_info, base_sequence, base_label)

    write_variant_fasta(args.output_fasta, rows)
    if args.report:
        write_report(args.report, report_rows)

    matches = count_matches(seqs, position_info)

    print(f"Input sequences:        {len(seqs)}", file=sys.stderr)
    print(f"Sequence length:        {seq_len}", file=sys.stderr)
    print(f"Inclusion proportion:   {args.proportion:.1%} of remaining mass", file=sys.stderr)
    print(f"Base sequence mode:     {mode_desc}", file=sys.stderr)
    print(f"Base sequence:          {base_sequence}", file=sys.stderr)
    print(f"Variant rows written:   {len(rows)} (1 base + {len(rows) - 1} variants)", file=sys.stderr)
    print(f"Input seqs matching the derived motif: {matches}/{len(seqs)}", file=sys.stderr)
    print(f"Output written to:      {args.output_fasta}", file=sys.stderr)
    if args.report:
        print(f"Report written to:      {args.report}", file=sys.stderr)


if __name__ == "__main__":
    main()