#!/bin/bash
# 02_run_all.sh
# Runs every system folder created by 01_prepare_sims.py, one after another.
# On Colab, run this from a cell with: !bash 02_run_all.sh
# Each system's own run.py was auto-generated by CALVADOS's Config.write(). 
# then CALVADOS generates the necessary run.py
# 02_run_all.sh
#      ↓
# python WT/run.py
#      ↓
# CALVADOS
#      ↓
# OpenMM
#      ↓
# forces + integration
#      ↓
# trajectory

set -e

for dir in */ ; do # Go through every folder in the current directory
    name="${dir%/}"
    if [ -f "${dir}run.py" ]; then # If this folder contains a run.py, treat it as one of the simulation systems
        echo "=================================================="
        echo "Running: ${name}"
        echo "=================================================="
        python "${dir}run.py" --path "${dir}"
    fi
done

echo "All systems finished."
